# Generated by Django 5.2 on 2025-06-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Class', models.CharField(max_length=30)),
                ('rno', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.teacher')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.subject')),
            ],
        ),
    ]
