# Generated by Django 5.2 on 2025-06-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0005_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.IntegerField(null=True),
        ),
    ]
