# Generated by Django 5.2 on 2025-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0006_alter_student_rno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
