# Generated by Django 5.2 on 2025-06-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0007_alter_student_rno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.teacher'),
        ),
    ]
