# Generated by Django 5.2 on 2025-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0008_alter_student_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
