# Generated by Django 5.2 on 2025-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0009_subject_slug_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
