# Generated by Django 5.2 on 2025-06-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0011_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_name',
        ),
    ]
