# Generated by Django 5.2 on 2025-06-20 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0012_remove_student_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Class', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('rno', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.subject')),
                ('teacher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.teacher')),
            ],
        ),
    ]
