# Generated by Django 5.2 on 2025-06-20 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0013_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='email',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default='04:23 AM'),
        ),
    ]
