# Generated by Django 5.2 on 2025-06-20 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0014_remove_attendance_contact_remove_attendance_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
