# Generated by Django 5.2 on 2025-06-20 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0015_alter_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 6, 20, 4, 30, 23, 591336, tzinfo=datetime.timezone.utc)),
        ),
    ]
