# Generated by Django 5.2 on 2025-06-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0016_alter_attendance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
