# Generated by Django 5.2 on 2025-06-20 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0017_remove_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 6, 20, 4, 32, 19, 986019, tzinfo=datetime.timezone.utc)),
        ),
    ]
