# Generated by Django 5.2 on 2025-06-20 04:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0020_alter_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
