# Generated by Django 5.2 on 2025-06-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0021_attendance_class_attendance_date_attendance_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Class',
            new_name='aclass',
        ),
    ]
