# Generated by Django 5.2 on 2025-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0022_rename_class_attendance_aclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='aclass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
