# Generated by Django 5.2 on 2025-06-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0025_attendance_aclass_attendance_date_attendance_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='aclass',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='rno',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
