# Generated by Django 5.2 on 2025-06-20 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0026_remove_attendance_aclass_remove_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='aclass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='adate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='agender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='aname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='arno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='asubject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ateacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='atime',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
