# Generated by Django 5.2 on 2025-06-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0027_attendance_aclass_attendance_adate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='aclass',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='adate',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='agender',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='aname',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='arno',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='asubject_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ateacher_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='atime',
        ),
    ]
