# Generated by Django 5.2 on 2025-06-20 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0028_remove_attendance_aclass_remove_attendance_adate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(blank=True, max_length=50)),
                ('aclass', models.CharField(blank=True, max_length=30)),
                ('agender', models.CharField(blank=True, max_length=10)),
                ('arno', models.CharField(max_length=20, null=True)),
                ('adate', models.DateField(default=django.utils.timezone.now)),
                ('atime', models.TimeField(default=django.utils.timezone.localtime)),
                ('asubject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.subject')),
                ('ateacher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendenceapp.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
