# Generated by Django 5.2 on 2025-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0029_allattendance_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allattendance',
            name='asubject_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allattendance',
            name='ateacher_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
