# Generated by Django 5.2.3 on 2025-06-20 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0030_alter_allattendance_asubject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allattendance',
            name='atime',
            field=models.CharField(default=django.utils.timezone.localtime, max_length=30),
        ),
    ]
