# Generated by Django 5.2.3 on 2025-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0031_alter_allattendance_atime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allattendance',
            name='adate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
