# Generated by Django 5.2.3 on 2025-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0033_classes_alter_allattendance_adate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes',
        ),
        migrations.AddField(
            model_name='subject',
            name='classname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
